export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';

// Errors
export const ERROR_ON_PRODUCTS = 'ERROR_ON_PRODUCTS';
export const ERROR_ON_CREATE_PRODUCT = 'ERROR_ON_CREATE_PRODUCT';